<?xml version="1.0"?>
<robot xmlns:xacro="http://wiki.ros.org/xacro" name="agv">
  <xacro:property name="wheel_radius" value="0.1"/>
  <xacro:property name="wheel_separation" value="0.3"/>
  <link name="base_link">
    <inertial><mass value="10"/><origin xyz="0 0 0"/><inertia ixx="0.1" iyy="0.1" izz="0.1"/></inertial>
    <visual><geometry><box size="0.5 0.3 0.1"/></geometry>
    <material><color rgba="0 0 1 1"/></material></visual>
    <collision><geometry><box size="0.5 0.3 0.1"/></geometry></collision>
  </link>
  <link name="left_wheel_link"><visual><geometry><cylinder length="0.05" radius="${wheel_radius}"/></geometry></visual></link>
  <link name="right_wheel_link"><visual><geometry><cylinder length="0.05" radius="${wheel_radius}"/></geometry></visual></link>
  <joint name="left_wheel_joint" type="continuous">
    <parent link="base_link"/><child link="left_wheel_link"/>
    <origin xyz="0 ${wheel_separation/2} 0" rpy="0 1.5708 0"/><axis xyz="0 0 1"/>
  </joint>
  <joint name="right_wheel_joint" type="continuous">
    <parent link="base_link"/><child link="right_wheel_link"/>
    <origin xyz="0 -${wheel_separation/2} 0" rpy="0 1.5708 0"/><axis xyz="0 0 1"/>
  </joint>
  <gazebo><plugin name="diff_drive_controller" filename="libgazebo_ros_diff_drive.so">
    <ros><namespace>/</namespace><remapping>cmd_vel:=cmd_vel</remapping></ros>
    <updateRate>100.0</updateRate>
    <leftJoint>left_wheel_joint</leftJoint><rightJoint>right_wheel_joint</rightJoint>
    <wheelSeparation>${wheel_separation}</wheelSeparation><wheelDiameter>${wheel_radius*2}</wheelDiameter>
  </plugin></gazebo>
</robot>
